Revert "conflicts"
This reverts commit 5d202ca0a73173fc7964d7e1ad70faaa10c924f2, reversing
changes made to 3ab2b2de21893d1f68404152bee7e10b4541b7e2.

diff --git a/model-downloader/bin/download b/model-downloader/bin/download
--- a/model-downloader/bin/download
+++ b/model-downloader/bin/download
@@ -10,10 +10,10 @@ if [ -f "$GLOVE_MODEL_FILE_PATH" ]; then
 else
   echo "$GLOVE_MODEL_FILE_PATH missing; downloading now ..."
   mkdir -p -- "${GLOVE_MODEL_FILE_PATH%/*}"
-  $HOME/.local/bin/gdown "${GLOVE_MODEL_GDRIVE_ID}&confirm=t" -O $GLOVE_MODEL_FILE_PATH
+  $HOME/.local/bin/gdown $GLOVE_MODEL_GDRIVE_ID -O $GLOVE_MODEL_FILE_PATH
 
   if [ ! -f "$GLOVE_MODEL_FILE_PATH" ]; then
-    >&2 echo "GloVe model not downloaded, aborting"
+    >&2 echo "GloVe model not downloaded, aborting."
     exit 1
   fi
 fi
@@ -27,7 +27,6 @@ else
   mkdir -p `dirname ${MODEL_DIR}/${LDA_MODEL_FILE}` && mv -f "${TEMP_DIR}/lda.gz" ${MODEL_DIR}/${LDA_MODEL_FILE}
 fi
 
-<<<<<<< HEAD
 if [ -d "${MODEL_DIR}/stanford-corenlp/" ]; then
   echo "${MODEL_DIR}/stanford-corenlp/ already present"
 else
@@ -50,17 +49,6 @@ else
   echo "${MODEL_DIR}/elmo/elmo.hdf5 missing; downloading now ..."
   mkdir -p "${MODEL_DIR}/elmo/"
   wget --continue -O "${MODEL_DIR}/elmo/elmo.hdf5" https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
-=======
-# ENV NLTK_MODEL_DIR=nltk
-if [ -d "/home/app/nltk_data" ]; then
-  echo "NLTK data packaged in container image; copying now ..."
-  mkdir -p $MODEL_DIR/$NLTK_MODEL_DIR
-  cp -Rf /home/app/nltk_data/* $MODEL_DIR/$NLTK_MODEL_DIR
-else
-  echo "NLTK data not packaged in container image;  downloading now ..."
-  python -m nltk.downloader -d $MODEL_DIR/$NLTK_MODEL_DIR $NLTK_PACKAGES
->>>>>>> 525df97f6286fd3f766792833cc11757a37fc363
 fi
 
 touch "${MODEL_DIR}/.done"
-echo "Model downloads succeeded"
